---
- name: Basic System Setup
  hosts: all
  become: false
  tasks:
    - name: Create a hello.txt file in the user's home directory
      ansible.builtin.copy:
        dest: ~/hello.txt
        content: "Hello from Ansible!"
   
    - name: Print a welcome message
      ansible.builtin.debug:
        msg: "Welcome to Ansible Automation Platform!"