---
- name: Basic System Setup
  hosts: all
  become: false
  tasks:
    - name: Create a hello.txt file in the user's home directory
      ansible.builtin.copy:
        dest: ~/hello.txt
        content: "{{ copy_content }}"
      register: hello_result
      when: ansible_facts['os_family'] == 'RedHat'
   
    - name: Print a welcome message
      ansible.builtin.debug:
        msg: "{{ welcome_message }}"
      when: ansible_facts['os_family'] == 'RedHat'
    
    - name: Task runs only if previous was successful
      ansible.builtin.debug:
        msg: "{{ item }}"
      when: hello_result.changed
      loop:
        -  "The previous task was succesfull"
        - "Playbook executed on a Linux host"
    - name: Create or update a file and notify handler
      ansible.builtin.file:
        path: ~/trigger.txt
        state: touch
      notify: Say file was touched 
    
    - name: Update MOTD from jinja template
      ansible.builtin.template:
        src: templates/motd.j2
        dest: ~/motd
  handlers:
    - name: Say file was touched
      ansible.builtin.debug:
        msg: "Handler was triggered because the file was changed."