---
- name: Basic System Setup
  hosts: all
  become: false
  tasks:
    - name: Create a hello.txt file in the user's home directory
      ansible.builtin.copy:
        dest: ~/hello.txt
        content: "Hello from Ansible!"
    - name: Update all security-related packages
      ansible.builtin.package:
        name: '*'
        state: latest
        security: true
   
    - name: Create a new user
      ansible.builtin.user:
        name: "carol"
        state: present
        create_home: true