---
- name: Basic System Setup
  hosts: all
  become: false
  tasks:
    - name: Ensure sudo is installed
      ansible.builtin.package:
        name: sudo
        state: present
    - name: Update all security-related packages
      ansible.builtin.package:
        name: '*'
        state: latest
        security: true
   
    - name: Create a new user
      ansible.builtin.user:
        name: "carol"
        state: present
        create_home: true