---
- name: Basic System Setup
  hosts: all
  become: false
  tasks:
    - name: Create a hello.txt file in the user's home directory
      ansible.builtin.copy:
        dest: ~/hello.txt
        content: "{{ copy_content }}"
   
    - name: Print a welcome message
      ansible.builtin.debug:
        msg: "{{ welcome_message }}"